uavcan_node_id:           42
uavcan_node_name:         "inno.dynamics"
bridges:                  ["ActuatorsUavcanToRos",              "/uav/actuators_raw",
                           "ArmUavcanToRos",                    "/uav/arm",

                           "BaroStaticPressureRosToUavcan",     "/uav/static_pressure",
                           "BaroStaticTemperatureRosToUavcan",  "/uav/static_temperature",
                           "DiffPressureRosToUavcan",           "/uav/raw_air_data",
                           "GpsRosToUavcan",                    "/uav/gps_position",
                           "ImuRosToUavcan",                    "/uav/imu",
                           "MagnetometerRosToUavcan",           "/uav/mag"
]
